name: lumina
description: A production-ready mental health platform connecting users and therapists
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  firebase_storage: ^11.5.6

  # UI & Animations
  flutter_animate: ^4.2.0+1
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0

  # State Management & Utils
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  uuid: ^4.2.1

  # Google Sign In
  google_sign_in: ^6.1.6

  # Icons & UI
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  firebase_app_check: ^0.2.1+8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true