name: lumina_ai
description: "AI-powered mental health companion that connects users to real-life therapists and provides personalized AI-driven support."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # State Management
  provider: ^6.1.1

  # HTTP & API calls
  http: ^1.1.2

  # Image handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # Audio/Video
  audioplayers: ^5.2.1
  video_player: ^2.8.2

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Notifications
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^14.7.10

  # UI Components
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.4
  share_plus: ^7.2.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2

  # Permissions
  permission_handler: ^11.2.0

  # Encryption & Security
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # Assets will be added later when we create the folders
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/audio/
  #   - assets/animations/

  # Fonts will be added later when we download them
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf