// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBnV38D7QEtBtKMCqeK9GoUM-zafSh3Vs',
    appId: '1:395769118596:web:3324a8658f81d2500ee7d1',
    messagingSenderId: '395769118596',
    projectId: 'lumina-391d8',
    authDomain: 'lumina-391d8.firebaseapp.com',
    storageBucket: 'lumina-391d8.firebasestorage.app',
    measurementId: 'G-QX2PQ2W2VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYNhQ2Gp_URGsFcYSddYp6qzMHQnWrPWY',
    appId: '1:395769118596:android:b0cd27461879caed0ee7d1',
    messagingSenderId: '395769118596',
    projectId: 'lumina-391d8',
    storageBucket: 'lumina-391d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_j1wa_rw1Gq2b1wIE0FmYKN0maAqFC_Q',
    appId: '1:395769118596:ios:52e1b293d8207b360ee7d1',
    messagingSenderId: '395769118596',
    projectId: 'lumina-391d8',
    storageBucket: 'lumina-391d8.firebasestorage.app',
    androidClientId: '395769118596-i4ro91g28vf3vo2sgjb0u15f02nl6bsl.apps.googleusercontent.com',
    iosClientId: '395769118596-4j8i14l69ap3k9pqme2r1oo2r8sa0ce4.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_j1wa_rw1Gq2b1wIE0FmYKN0maAqFC_Q',
    appId: '1:395769118596:ios:52e1b293d8207b360ee7d1',
    messagingSenderId: '395769118596',
    projectId: 'lumina-391d8',
    storageBucket: 'lumina-391d8.firebasestorage.app',
    androidClientId: '395769118596-i4ro91g28vf3vo2sgjb0u15f02nl6bsl.apps.googleusercontent.com',
    iosClientId: '395769118596-4j8i14l69ap3k9pqme2r1oo2r8sa0ce4.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBnV38D7QEtBtKMCqeK9GoUM-zafSh3Vs',
    appId: '1:395769118596:web:34e8e0f1814a26900ee7d1',
    messagingSenderId: '395769118596',
    projectId: 'lumina-391d8',
    authDomain: 'lumina-391d8.firebaseapp.com',
    storageBucket: 'lumina-391d8.firebasestorage.app',
    measurementId: 'G-11Z8C8MWEB',
  );
}
